---
- name: Update all hosts
  hosts: all
  gather_facts: no
  vars_files:
  - /opt/ansible/vars/login.yaml
  tasks:

  - include: template_poweron.yaml
    when: '"centos" or "debian" in inventory_hostname'

  - name: Gather facts
    tags:
    - always
    setup:


  - include: debian.yaml
    when: ansible_os_family == 'Debian'


  - include: redhat.yaml
    when: ansible_os_family == 'RedHat'

  - include: template_shutdown.yaml
    when: '"centos" or "debian" in inventory_hostname'
