- name: Convert CentOS template to VM
  tags:
  - template
  vmware_guest:
    hostname: "{{ vcenter_host }}"
    username: "{{ vcenter_un }}"
    password: "{{ vcenter_pw }}"
    validate_certs: False
    name: "centos8-template"
    datacenter: Datacenter
    folder: /Templates
    state: present
    is_template: False
  run_once: True
  delegate_to: localhost

- name: Convert Debian template to VM
  tags:
  - template
  vmware_guest:
    hostname: "{{ vcenter_host }}"
    username: "{{ vcenter_un }}"
    password: "{{ vcenter_pw }}"
    validate_certs: False
    name: "debian-template"
    datacenter: Datacenter
    folder: /Templates
    state: present
    is_template: False
  run_once: True
  delegate_to: localhost

- name: Turn on CentOS template VM
  tags:
  - template
  vmware_guest:
    hostname: "{{ vcenter_host }}"
    username: "{{ vcenter_un }}"
    password: "{{ vcenter_pw }}"
    validate_certs: False
    name: "centos8-template"
    datacenter: Datacenter
    folder: /Templates
    state: poweredon
    wait_for_ip_address: yes
  run_once: True
  delegate_to: localhost

- name: Turn on Debian template VM
  tags:
  - template
  vmware_guest:
    hostname: "{{ vcenter_host }}"
    username: "{{ vcenter_un }}"
    password: "{{ vcenter_pw }}"
    validate_certs: False
    name: "debian-template"
    datacenter: Datacenter
    folder: /Templates
    state: poweredon
    wait_for_ip_address: yes
  run_once: True
  delegate_to: localhost
