---
- name: Update host
  hosts: "{{ hostname }}"
  gather_facts: yes
  vars_files: 
  - ../cloneVM/vars.yaml
  - /opt/ansible/vars/login.yaml
  - ./vars.yaml
  tasks:

  - name: Update Debian host
    include_tasks: /opt/ansible/pb/updateHosts/debian.yaml
    when: ansible_os_family == 'Debian'


  - name: Update RedHat host
    include_tasks: /opt/ansible/pb/updateHosts/redhat.yaml
    when: ansible_os_family == 'RedHat'
