all:
  hosts:
    dns.torset.me:
    ldap.torset.me:
  children:
    centos:
      children:
        centos8:
          hosts:
            ansible.torset.me:
            vm2:
            ansible_test:
    debian:
      children:
        debian9:
          hosts:
        debian10:
          hosts:
            docker.torset.me:
            unifi.torset.me:
    bsd:
      children:
        freebsd:
          hosts:
            freenas.torset.me:
            pfsense.torset.me:

