- name: Update Debian packages
  tags:
  - pkg
  - pkg_update
  become: yes
  apt:
    update_cache: true
    upgrade: safe
    autoremove: yes


- name: Check for Debian reboot hint
  stat:
    path: /var/run/reboot-required
  register: deb_reboot_hint


- name: Reboot hosts
  become: yes
  reboot:
    connect_timeout: 60
  when: (ansible_os_family == 'Debian') and (deb_reboot_hint.stat.exists)
  register: rebooting
