---
- name: Add repo
  become: yes
  apt_repository:
    repo: deb https://repos.influxdata.com/debian {{ ansible_distribution_release }} stable
    state: present
    filename: telegraf

- name: Install telegraf
  become: yes
  apt:
    name: telegraf
    state: present
