---

#Install Telegraf client
- name: Add InfluxDB repo
  become: yes
  template:
    src: templates/influxdb.repo.j2
    dest: /etc/yum.repos.d/influxdb.repo
    owner: root
    group: root
    mode: "0644"

- name: Install Telegraf
  become: yes
  dnf:
    name: telegraf
    state: latest
